export const GET_PLAYERS_CHARACTERS = 'GET_PLAYERS_CHARACTERS'
export const GET_PLAYERS_CHARACTERS_SUCCESS = 'GET_PLAYERS_CHARACTERS_SUCCESS'
export const GET_PLAYERS_CHARACTERS_ERROR = 'GET_PLAYERS_CHARACTERS_ERROR'
