export const GET_PLAYERS_CHARACTERS = 'GET_PLAYERS_CHARACTERS'
export const GET_PLAYERS_CHARACTERS_SUCCESS = 'GET_PLAYERS_CHARACTERS_SUCCESS'
export const GET_PLAYERS_CHARACTERS_ERROR = 'GET_PLAYERS_CHARACTERS_ERROR'

export const GET_PLAYER_CHARACTER = 'GET_PLAYER_CHARACTER'
export const GET_PLAYER_CHARACTER_SUCCESS = 'GET_PLAYER_CHARACTER_SUCCESS'
export const GET_PLAYER_CHARACTER_ERROR = 'GET_PLAYER_CHARACTER_ERROR'
