export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'

export const GET_AUTH_INFO = 'GET_AUTH_INFO'
export const GET_AUTH_INFO_SUCCESS = 'GET_AUTH_INFO_SUCCESS'
export const GET_AUTH_INFO_ERROR = 'GET_AUTH_INFO_ERROR'
