export const GET_PLAYER_CHARACTERS = 'GET_PLAYER_CHARACTERS'
export const GET_PLAYER_CHARACTERS_SUCCESS = 'GET_PLAYER_CHARACTERS_SUCCESS'
export const GET_PLAYER_CHARACTERS_ERROR = 'GET_PLAYER_CHARACTERS_ERROR'
