export const GET_TALENTS = 'GET_TALENTS'
export const GET_TALENTS_SUCCESS = 'GET_TALENTS_SUCCESS'
export const GET_TALENTS_ERROR = 'GET_TALENTS_ERROR'

export const ADD_TALENT = 'ADD_TALENT'
export const ADD_TALENT_SUCCESS = 'ADD_TALENT_SUCCESS'
export const ADD_TALENT_ERROR = 'ADD_TALENT_ERROR'

export const ADD_PLAYER_CHARACTER_TALENT = 'ADD_PLAYER_CHARACTER_TALENT'
export const ADD_PLAYER_CHARACTER_TALENT_SUCCESS =
  'ADD_PLAYER_CHARACTER_TALENT_SUCCESS'
export const ADD_PLAYER_CHARACTER_TALENT_ERROR =
  'ADD_PLAYER_CHARACTER_TALENT_ERROR'
