export const GET_CRITICAL_INJURIES = 'GET_CRITICAL_INJURIES'
export const GET_CRITICAL_INJURIES_SUCCESS = 'GET_CRITICAL_INJURIES_SUCCESS'
export const GET_CRITICAL_INJURIES_ERROR = 'GET_CRITICAL_INJURIES_ERROR'

export const ADD_PLAYER_CHARACTER_CRITICAL_INJURY =
  'ADD_PLAYER_CHARACTER_CRITICAL_INJURY'
export const ADD_PLAYER_CHARACTER_CRITICAL_INJURY_SUCCESS =
  'ADD_PLAYER_CHARACTER_CRITICAL_INJURY_SUCCESS'
export const ADD_PLAYER_CHARACTER_CRITICAL_INJURY_ERROR =
  'ADD_PLAYER_CHARACTER_CRITICAL_INJURY_ERROR'
