export const GET_CRITICAL_INJURIES = 'GET_CRITICAL_INJURIES'
export const GET_CRITICAL_INJURIES_SUCCESS = 'GET_CRITICAL_INJURIES_SUCCESS'
export const GET_CRITICAL_INJURIES_ERROR = 'GET_CRITICAL_INJURIES_ERROR'
