export const GET_WEAPONS = 'GET_WEAPONS'
export const GET_WEAPONS_SUCCESS = 'GET_WEAPONS_SUCCESS'
export const GET_WEAPONS_ERROR = 'GET_WEAPONS_ERROR'

export const ADD_WEAPON = 'ADD_WEAPON'
export const ADD_WEAPON_SUCCESS = 'ADD_WEAPON_SUCCESS'
export const ADD_WEAPON_ERROR = 'ADD_WEAPON_ERROR'
